use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'

pod 'GoogleMaps'
pod 'AFNetworking', '~> 2.5'
pod 'BDBOAuth1Manager'
pod 'Polyline', '~> 3.0'

target '1-way-destination' do
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
end
